In [2]:
import csv
import numpy as np
import pandas as pd

In [54]:
arr = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19], [20, 21, 22, 23, 24]]
print([arr[:3] for arr in arr[2:]])

[[10, 11, 12], [15, 16, 17], [20, 21, 22]]


In [ ]:
arr = np.arange(25).reshape(5, 5)
print(arr[1:3, :2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [62]:
arr = np.arange(25).reshape(5, 5)
print(arr[::2, : :])

[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]]
